language: node_js
node_js:
 - "node"
env:
- MY_VAR=EverythingIsAwesome
- NODE_ENV=TEST
secure: "ImzPOQ6UVxM028K9DO4Y/349TrTQRBnxk3EOm3X+ceiYgiK3bsW7hGMEIagH0nUiSuOn4QmDrEkiHPSLtvKnJjRnsy2Z9ERFK96/1e5Vj8k/YXGEGjpwYCcbot2jhJRbBaAGq2WIYHyzizmPfLqsHwRh5wCMhOYrb2m9PWiLNwZRab5i8TD7se24L9+OwpS8+AOWpB+HFrCoxT3+3W6xRI++aPWtaZeITN+P2wd5uCuGMb1/nJi1sm+AWT9c2mW0Ouk5eFwgZMxqMuscgwNpMfipXB7qE1olnTxumbphOH4297EvALB9fj6D5ofkdbcBq5+HzvUHdajK2UFNL0JBg0CCGUtClgog9M9PAr+nZ+Q3G5Pt76Ud3jSukh9fOhKIF4w9r12+F0K5kSfGs+WKVVEcY43HtSTk2wnjALb2wGDEV8xfR6raeBhPV0YFVLyz2xUpwPsrM4nHLI/chXqpfuuGrY+y4Y98ShLaBqusxmgYwyg7VT4LceoKPZ0BrA2GAAsKA5DEzf8UbR8cloWgMzQWZhab6MF0sZS1vQv5qFDZekll3sLtNoXPLjP3gwOOM0/7DTVcZqAqybH2zm9gIZlGc+Eqwu0qEdNk0QvLVL61LVDmn0wqCEsYTF1ahbirvu1n98kvbzJ+1ui317dAExj1qMLmS38Dr5X5hf2bFUk="
